require:
  - standard
  - rubocop-rails
  - rubocop-performance
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.3.0
  NewCops: enable

inherit_gem:
  standard: config/base.yml

Rails/Output:
  Exclude:
    - 'app/views/**/*.rb'

