require:
  - standard
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable

inherit_gem:
  standard: config/base.yml

Rails/Output:
  Exclude:
    - 'app/views/**/*.rb'

