# fly.toml app configuration file generated for beagle-next on 2023-05-16T20:16:11+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "beagle-next"
primary_region = "sea"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  [build.args]
    BUILD_COMMAND = "bin/rails fly:build"
    SERVER_COMMAND = "bin/rails fly:run[server]"

[deploy]
  release_command = "bin/rails fly:release"

[env]
  PORT = "8080"
  PRIMARY_REGION = "sea"

[processes]
  web = "bin/rails fly:run[server]"
  workers = "bin/rails fly:run[sidekiq]"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["web"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "requests"
    hard_limit = 15
    soft_limit = 10

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
