default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5  } %>

development:
  <<: *default
  database: beagle_development

test:
  <<: *default
  database: beagle_test
  host: <%= ENV.fetch("DB_HOST", 'localhost') %>
  user: <%= ENV.fetch("DB_USER", '') %>
  password: <%= ENV.fetch("DB_PASSWORD", '') %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
