test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

cloudflare:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:cloudflare, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:cloudflare, :secret_access_key) %>
  endpoint: <%= Rails.application.credentials.dig(:cloudflare, :endpoint) || "https://r2.cloudflarestorage.com" %>
  bucket: <%= Rails.application.credentials.dig(:cloudflare, :bucket) || "bucket" %>
  region: auto
