name: RubocopBrancher
on: pull_request

env:
  RAILS_ENV: test

jobs:
  brancher:
    name: Run
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install gems
        run: bundle install

      - name: Get Changed Files
        id: changed_files
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          TOKEN=${{ github.token }}
          API_URL="https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/files"

          echo "files="$(curl -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github.v3+json" -s $API_URL | jq -r '.[].filename' | tr '\n' ' ')"" >> $GITHUB_OUTPUT

      - name: Run linters
        id: linter
        run: |
          # bundle exec rubocop --fail-fast --force-exclusion --format=github ${{steps.changed_files.outputs.files}}
          has_issues=$(bundle exec rubocop --fail-fast --force-exclusion --format=files ${{steps.changed_files.outputs.files}} > /dev/null 2>&1; echo $?)
          echo "has_issues="$has_issues"" >> $GITHUB_OUTPUT

          if [ "$has_issues" == "1"  ]; then
            bundle exec rubocop --format=markdown --force-exclusion ${{steps.changed_files.outputs.files}} > rubocop-brancher.txt
            bundle exec rubocop --autocorrect --force-exclusion ${{steps.changed_files.outputs.files}}
          fi

      - name: Extract branch name
        if: steps.linter.outputs.has_issues == '1'
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Create Pull Request
        id: create_pull
        if: steps.linter.outputs.has_issues == '1'
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Autogenerated PR to fix rubocop issues in the PR #${{ github.event.pull_request.number }}"
          body-path: rubocop-brancher.txt
          base: ${{ steps.extract_branch.outputs.branch }}
          commit-message: "Fix rubocop issues by RubocopBrancher workflow"
          branch: ${{ steps.extract_branch.outputs.branch }}-rubocop_brancher
          delete-branch: true

