name: RubocopBrancher
on: [push, pull_request]

env:
  RAILS_ENV: test

jobs:
  brancher:
    name: Linters
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: false

      - name: Install gems
        run: echo ${{ github.event.pull_request }}

      # - name: Install gems
        # run: bundle install

      # - name: Run linters
        # run: bundle exec rubocop
