name: RubocopBrancher
on: pull_request

env:
  RAILS_ENV: test

jobs:
  brancher:
    name: RubocopBrancher
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install gems
        run: bundle install

      - name: Get Changed Files
        id: changed_files
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          TOKEN=${{ github.token }}
          API_URL="https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/files"

          echo "files="$(curl -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github.v3+json" -s $API_URL | jq -r '.[].filename' | tr '\n' ' ')"" >> $GITHUB_OUTPUT

      - name: Run linters
        run: |
          has_issues=$(bundle exec rubocop --fail-fast --force-exclusion ${{steps.changed_files.outputs.files}} --format=github)

          if [[ $has_issues ]]; then
            echo "Has issues"
          else
            echo "Has no issues"
          fi

